# Generated by Django 2.0.1 on 2018-01-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cssmigrate_20180104_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
